# Generated by Django 4.2.4 on 2023-10-27 04:52

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Post.models.upload_picture_path),
        ),
    ]
