# Generated by Django 4.2.4 on 2023-11-13 06:51

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=Post.models.upload_video_path),
        ),
    ]
