# Generated by Django 4.2.7 on 2023-11-13 20:51

import accounts.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images')),
                ('profile_cover', models.ImageField(blank=True, default='img.png', null=True, upload_to='profile_covers')),
                ('profile_song', models.FileField(blank=True, default=None, upload_to=accounts.models.get_profile_song_filepath)),
                ('profile_background', models.ImageField(blank=True, default='background.png', null=True, upload_to='profile_backgrounds')),
                ('hide_email', models.BooleanField(default=True)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('backgroundColor', colorfield.fields.ColorField(default='#FE8116', image_field=None, max_length=25, samples=None)),
                ('fontColor', colorfield.fields.ColorField(default='#24262e', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
