# Generated by Django 4.2.4 on 2023-10-09 07:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to=accounts.models.get_profile_image_filepath)),
                ('profile_cover', models.ImageField(blank=True, default=accounts.models.get_default_profile_cover, null=True, upload_to=accounts.models.get_profile_cover_filepath)),
                ('profile_background', models.ImageField(blank=True, default=accounts.models.get_default_profile_background, null=True, upload_to=accounts.models.get_profile_background_filepath)),
                ('profile_song', models.FileField(blank=True, null=True, upload_to=accounts.models.get_profile_song_filepath)),
                # ('profile_background', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_background_filepath)),

                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
