# Generated by Django 4.2.4 on 2023-10-25 15:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='color',
            field=colorfield.fields.ColorField(default='#fe8116', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='font_preference',
            field=models.CharField(default='"Poppins", sans-serif', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
