# Generated by Django 4.2.4 on 2023-10-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_bio_useraccount_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='backgroundColor',
            field=models.TextField(default='linear-gradient(to right, rgba(44,15,85,0.9), rgba(44,15,38, 0.9))'),
        ),
    ]
