# Generated by Django 4.2.4 on 2023-10-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_backgroundcolor'),
        ('accounts', '0007_alter_useraccount_color'),
    ]

    operations = [
    ]
