# Generated by Django 4.2.4 on 2023-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20231027_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='backgroundColor',
            field=models.TextField(default='linear-gradient(to right, rgba(44,15,85,0.9), rgba(44,15,38, 0.9))'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='get_profile_image_filepath'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_cover',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='get_profile_cover_filepath'),
        ),
    ]
