# Generated by Django 4.2.4 on 2023-11-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_profile_song'),
        ('accounts', '0010_location'),
    ]

    operations = [
    ]
