# Generated by Django 4.2.4 on 2023-11-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20231101_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_cover',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='get_profile_image_filepath'),
        ),
    ]
