# Generated by Django 4.2.4 on 2023-11-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_background',
            field=models.ImageField(blank=True, default='background.png', null=True, upload_to='profile_backgrounds'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_cover',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_covers'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_images'),
        ),
    ]
