# Generated by Django 4.2.4 on 2023-11-01 07:02

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_useraccount_profile_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='linear-gradient(to right, rgba(44,15,85,0.9), rgba(44,15,38, 0.9))', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_cover',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_covers'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images'),
        ),
    ]
