# Generated by Django 4.2.4 on 2023-11-13 09:59

import accounts.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_useraccount_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='font_preference',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fontColor',
            field=colorfield.fields.ColorField(default='linear-gradient(to right, rgba(44,15,85,0.9), rgba(44,15,38, 0.9))', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_song',
            field=models.FileField(blank=True, default=None, upload_to=accounts.models.get_profile_song_filepath),
        ),
    ]
