# Generated by Django 4.2.4 on 2023-11-13 18:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_useraccount_font_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#FE8116', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fontColor',
            field=colorfield.fields.ColorField(default='#24262e', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_cover',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='profile_covers'),
        ),
    ]
